project:
  type: book
  output-dir: _output

number-depth: 2

book:
  title: "WIP"
  author: "Renata Hirota"
  date: "2025"
  chapters:
  - index.qmd
  - 01_abstract.qmd
  - 02_introduction.qmd
  - 03_literature_review.qmd
  - 04_methodology.qmd
  - 05_results.qmd
  - 06_discussion.qmd
  - 07_conclusion.qmd
  - 08_references.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  # epub:
  #   cover-image: cover.png